### ISSUE TITLE
miss a file? `./src/page`

### ISSUE THREAD

**Issue by hysios** [react-china/forum-frontend#6]
```bash
❯ gulp html                                                                                                                                                                      
[12:08:19]
[12:10:08] Requiring external module coffee-script/register
[12:10:10] Using gulpfile ~/Documents/forum-frontend/gulpfile.coffee
[12:10:10] Starting 'html'...
[12:10:12] 'html' errored after 1.15 s
[12:10:12] Error: Cannot find module './src/page'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/hysios/Documents/forum-frontend/template.cirru:6:32)
  at Module._compile (module.js:460:26)
  at Object.require.extensions..cirru (/Users/hysios/Documents/forum-frontend/node_modules/cirru-script/lib/register.js:12:19)
  at Module.load (/Users/hysios/Documents/forum-frontend/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
```

**Comment by jiyinyiyong** [comment]
具体需要看原先的项目了, 因为 CoffeeScript 被排斥的原因, 我没有拷贝所有文件过来. https://github.com/teambition/coffee-webpack-starter

**Comment by hysios** [comment]
@jiyinyiyong 我尝试了解决一下这问题，还是有点麻烦，我能提交一个新的框架吗

**Comment by jiyinyiyong** [comment]
先提交吧, 有问题再改.

**Comment by fraserxu** [comment]
CoffeeScript :scream:

**Comment by shane13hsi** [comment]
Discourse 就是从 CoffeeScript 转成 JavaScript 的。原因就是 JavaScript 更容易吸引 PR。

**Comment by jiyinyiyong** [comment]
更多人喜欢的方案, 确实人数是说服力的事情.

**Comment by uooo** [comment]
我现在做东西就是，只要方向正确都随大流，哈哈

**Comment by geminiyellow** [comment]
我 PR 了，谁去看看整理一下吧。别 CoffeeScript 了。原先我本来打算把 Js，Ts，Cs 全部弄进去的，想想算了。纯粹点。

**Comment by Justinidlerz** [comment]
其实现在ES6做编译的话可以不用那些coffeeScript之类的东西进行二次编译了，ES6就够方便的了

**Comment by gangdiedao** [comment]
CoffeeScript  看不懂呀

**Comment by uooo** [comment]
CoffeeScript 都会修改为 ES6的

**Comment by xcatliu** [comment]
> CoffeeScript 都会修改为 ES6 的，后续项目基于 ES2015+ 开发

赞！
